//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCH_STEP_EXECUTION
    {
        public long STEP_EXECUTION_ID { get; set; }
        public long VERSION { get; set; }
        public string STEP_NAME { get; set; }
        public long JOB_EXECUTION_ID { get; set; }
        public System.DateTime START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public string STATUS { get; set; }
        public Nullable<long> COMMIT_COUNT { get; set; }
        public Nullable<long> READ_COUNT { get; set; }
        public Nullable<long> FILTER_COUNT { get; set; }
        public Nullable<long> WRITE_COUNT { get; set; }
        public Nullable<long> READ_SKIP_COUNT { get; set; }
        public Nullable<long> WRITE_SKIP_COUNT { get; set; }
        public Nullable<long> PROCESS_SKIP_COUNT { get; set; }
        public Nullable<long> ROLLBACK_COUNT { get; set; }
        public string EXIT_CODE { get; set; }
        public string EXIT_MESSAGE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
    
        public virtual BATCH_JOB_EXECUTION BATCH_JOB_EXECUTION { get; set; }
        public virtual BATCH_STEP_EXECUTION_CONTEXT BATCH_STEP_EXECUTION_CONTEXT { get; set; }
    }
}
