//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_API_RESOURCE
    {
        public T_API_RESOURCE()
        {
            this.T_DIM_RESOURCE_API = new HashSet<T_DIM_RESOURCE_API>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string RouteTemplate { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<byte> IsPrivilegeRestrict { get; set; }
    
        public virtual ICollection<T_DIM_RESOURCE_API> T_DIM_RESOURCE_API { get; set; }
    }
}
