//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COL_ORIGINAL_DATAVALUE
    {
        public int ID { get; set; }
        public int STRUCTURE_ID { get; set; }
        public int SAFETY_FACTOR_TYPE_ID { get; set; }
        public int SENSOR_ID { get; set; }
        public System.DateTime ACQUISITION_DATETIME { get; set; }
        public string MODULE_NO { get; set; }
        public Nullable<byte> CHANNEL_NUMBER { get; set; }
        public Nullable<decimal> CollectOriginalValue1 { get; set; }
        public Nullable<decimal> CollectOriginalValue2 { get; set; }
        public Nullable<decimal> CollectOriginalValue3 { get; set; }
        public Nullable<decimal> CollectOriginalValue4 { get; set; }
    }
}
