//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DATA_AGGREGATION
    {
        public int Id { get; set; }
        public int DateTimeId { get; set; }
        public int StructureId { get; set; }
        public int SafeFactorId { get; set; }
        public int SensorId { get; set; }
        public int AggDataTypeId { get; set; }
        public int AggCofigId { get; set; }
        public Nullable<decimal> CureentData1 { get; set; }
        public Nullable<decimal> CureentData2 { get; set; }
        public Nullable<decimal> CureentData3 { get; set; }
        public Nullable<decimal> CureentData4 { get; set; }
        public Nullable<decimal> Dlt1 { get; set; }
        public Nullable<decimal> Dlt2 { get; set; }
        public Nullable<decimal> Dlt3 { get; set; }
        public Nullable<decimal> Dlt4 { get; set; }
    
        public virtual T_DIM_AGG_CONFIG T_DIM_AGG_CONFIG { get; set; }
        public virtual T_DIM_AGG_TYPE T_DIM_AGG_TYPE { get; set; }
        public virtual T_DIM_DATETIME T_DIM_DATETIME { get; set; }
        public virtual T_DIM_SAFETY_FACTOR_TYPE T_DIM_SAFETY_FACTOR_TYPE { get; set; }
        public virtual T_DIM_SENSOR T_DIM_SENSOR { get; set; }
        public virtual T_DIM_STRUCTURE T_DIM_STRUCTURE { get; set; }
    }
}
