//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_REMOTE_DTU
    {
        public T_DIM_REMOTE_DTU()
        {
            this.T_DIM_DTU_STATUS = new HashSet<T_DIM_DTU_STATUS>();
            this.T_DIM_STRUCT_DTU = new HashSet<T_DIM_STRUCT_DTU>();
        }
    
        public int ID { get; set; }
        public string REMOTE_DTU_NUMBER { get; set; }
        public string REMOTE_DTU_SUBSCRIBER { get; set; }
        public Nullable<short> REMOTE_DTU_GRANULARITY { get; set; }
        public Nullable<bool> REMOTE_DTU_STATE { get; set; }
        public Nullable<System.DateTime> REMOTE_DTU_LAST_ONLINE_TIME { get; set; }
        public Nullable<System.DateTime> REMOTE_DTU_LAST_HEARTBEAT_TIME { get; set; }
        public Nullable<byte> HEARTBEAT_LOST_COUNT { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> DTU_PORT { get; set; }
        public string DTU_IP { get; set; }
        public int M200901 { get; set; }
        public int ProductDtuId { get; set; }
        public string P1 { get; set; }
        public string P2 { get; set; }
        public string P3 { get; set; }
        public string P4 { get; set; }
        public string DtuIp2 { get; set; }
        public Nullable<int> DtuPort2 { get; set; }
        public string DtuIp3 { get; set; }
        public Nullable<int> DtuPort3 { get; set; }
        public string DtuMode { get; set; }
        public Nullable<int> PacketSize { get; set; }
        public Nullable<int> PacketInterval { get; set; }
        public Nullable<int> ReconnectionCount { get; set; }
    
        public virtual T_DIM_DTU_PRODUCT T_DIM_DTU_PRODUCT { get; set; }
        public virtual ICollection<T_DIM_DTU_STATUS> T_DIM_DTU_STATUS { get; set; }
        public virtual ICollection<T_DIM_STRUCT_DTU> T_DIM_STRUCT_DTU { get; set; }
    }
}
