//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_AGG_CONFIG
    {
        public T_DIM_AGG_CONFIG()
        {
            this.T_DATA_AGGREGATION = new HashSet<T_DATA_AGGREGATION>();
        }
    
        public int Id { get; set; }
        public int StructureId { get; set; }
        public int FacotrId { get; set; }
        public int AggTypeId { get; set; }
        public int AggWayId { get; set; }
        public int DataBeginHour { get; set; }
        public int DataEndHour { get; set; }
        public Nullable<int> DateBegin { get; set; }
        public Nullable<int> DateEnd { get; set; }
        public string TimeMode { get; set; }
        public bool IsEnable { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<T_DATA_AGGREGATION> T_DATA_AGGREGATION { get; set; }
        public virtual T_DIM_AGG_TYPE T_DIM_AGG_TYPE { get; set; }
        public virtual T_DIM_AGG_WAY T_DIM_AGG_WAY { get; set; }
        public virtual T_DIM_SAFETY_FACTOR_TYPE T_DIM_SAFETY_FACTOR_TYPE { get; set; }
        public virtual T_DIM_STRUCTURE T_DIM_STRUCTURE { get; set; }
    }
}
