//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_PRODUCTCATAGORY_ORIGINALDATA
    {
        public int Id { get; set; }
        public Nullable<int> ProductCatagoryId { get; set; }
        public string OriginalTableName { get; set; }
        public Nullable<int> ColumnNumber { get; set; }
        public string ValueColumnName { get; set; }
        public string ValueColumn { get; set; }
        public string ValueDecimalDigits { get; set; }
        public string ValueUnit { get; set; }
    }
}
