//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_REGION_TYPE
    {
        public T_DIM_REGION_TYPE()
        {
            this.T_DIM_REGION = new HashSet<T_DIM_REGION>();
        }
    
        public short REGION_TYPE_ID { get; set; }
        public string REGION_TYPE_NAME_CN { get; set; }
        public string REGION_TYPE_NAME_EN { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<T_DIM_REGION> T_DIM_REGION { get; set; }
    }
}
