//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_DAI_PRODUCT
    {
        public T_DIM_DAI_PRODUCT()
        {
            this.T_DIM_DAI = new HashSet<T_DIM_DAI>();
            this.T_DIM_DAI1 = new HashSet<T_DIM_DAI>();
        }
    
        public int DAI_ID { get; set; }
        public Nullable<short> PROTOCOL_ID { get; set; }
        public string PRODUCT_TYPE_ID { get; set; }
        public Nullable<short> POWER_SUPPLY_TYPE_ID { get; set; }
        public Nullable<int> DAI_PRODUCT_TYPE_ID { get; set; }
        public Nullable<int> PROTOCOL_TYPE_ID { get; set; }
        public Nullable<short> DAI_CHANNEL_NUMBER { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> FormulaID { get; set; }
        public string PRODUCT_MODEL { get; set; }
    
        public virtual ICollection<T_DIM_DAI> T_DIM_DAI { get; set; }
        public virtual ICollection<T_DIM_DAI> T_DIM_DAI1 { get; set; }
        public virtual T_DIM_PROTOCOL_TYPE T_DIM_PROTOCOL_TYPE { get; set; }
        public virtual T_DIM_POWER_SUPPLY_TYPE T_DIM_POWER_SUPPLY_TYPE { get; set; }
        public virtual T_DIM_FORMULAID T_DIM_FORMULAID { get; set; }
        public virtual T_DIM_PRODUCT_TYPE T_DIM_PRODUCT_TYPE { get; set; }
    }
}
