//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_FORMULA_PARA
    {
        public T_DIM_FORMULA_PARA()
        {
            this.T_DIM_FORMULAID_SET = new HashSet<T_DIM_FORMULAID_SET>();
        }
    
        public int FormulaParaID { get; set; }
        public Nullable<int> FormulaID { get; set; }
        public Nullable<int> ParaNameID { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual T_DIM_FORMULAID T_DIM_FORMULAID { get; set; }
        public virtual ICollection<T_DIM_FORMULAID_SET> T_DIM_FORMULAID_SET { get; set; }
        public virtual T_DIM_FORMULA_PARA_NAME T_DIM_FORMULA_PARA_NAME { get; set; }
    }
}
