//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_PRODUCT_TYPE
    {
        public T_DIM_PRODUCT_TYPE()
        {
            this.T_DIM_DAI_PRODUCT = new HashSet<T_DIM_DAI_PRODUCT>();
            this.T_DIM_SENSOR_PRODUCT = new HashSet<T_DIM_SENSOR_PRODUCT>();
        }
    
        public string PRODUCT_TYPE_ID { get; set; }
        public string PRODUCT_TYPE_NAME { get; set; }
        public string PARENT_PRODUCT_TYPE_ID { get; set; }
        public Nullable<int> PRODUCT_LEVEL { get; set; }
        public Nullable<int> PRODUCT_TYPE_KEY { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<T_DIM_DAI_PRODUCT> T_DIM_DAI_PRODUCT { get; set; }
        public virtual T_DIM_PRODUCT_CATEGORY T_DIM_PRODUCT_CATEGORY { get; set; }
        public virtual ICollection<T_DIM_SENSOR_PRODUCT> T_DIM_SENSOR_PRODUCT { get; set; }
    }
}
