//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_ABNORMALSENSOR_CONFIG
    {
        public int SensorId { get; set; }
        public Nullable<decimal> ReplaceValue1 { get; set; }
        public Nullable<decimal> ReplaceValue2 { get; set; }
        public Nullable<decimal> ReplaceValue3 { get; set; }
        public Nullable<decimal> ReplaceValue4 { get; set; }
        public bool IsEnabled { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ConfigTime { get; set; }
    }
}
