//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_DTU_PRODUCT
    {
        public T_DIM_DTU_PRODUCT()
        {
            this.T_DIM_REMOTE_DTU = new HashSet<T_DIM_REMOTE_DTU>();
        }
    
        public int ProductId { get; set; }
        public string DtuFactory { get; set; }
        public string DtuModel { get; set; }
        public string NetworkType { get; set; }
    
        public virtual ICollection<T_DIM_REMOTE_DTU> T_DIM_REMOTE_DTU { get; set; }
    }
}
