//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_DATETIME
    {
        public T_DIM_DATETIME()
        {
            this.T_AGG__DAY_SAFETY_FACTOR_SCORE = new HashSet<T_AGG__DAY_SAFETY_FACTOR_SCORE>();
            this.T_AGG__DAY_STRUCTURE_SCORE = new HashSet<T_AGG__DAY_STRUCTURE_SCORE>();
            this.T_AGG__HOUR_SAFETY_FACTOR_SCORE = new HashSet<T_AGG__HOUR_SAFETY_FACTOR_SCORE>();
            this.T_AGG__HOUR_STRUCTURE_SCORE = new HashSet<T_AGG__HOUR_STRUCTURE_SCORE>();
            this.T_AGG__MONTH_SAFETY_FACTOR_SCORE = new HashSet<T_AGG__MONTH_SAFETY_FACTOR_SCORE>();
            this.T_AGG__MONTH_STRUCTURE_SCORE = new HashSet<T_AGG__MONTH_STRUCTURE_SCORE>();
            this.T_AGG__WEEK_STRUCTURE_SCORE = new HashSet<T_AGG__WEEK_STRUCTURE_SCORE>();
            this.T_AGG_WEEK_SAFETY_FACTOR_SCORE = new HashSet<T_AGG_WEEK_SAFETY_FACTOR_SCORE>();
            this.T_DATA_AGGREGATION = new HashSet<T_DATA_AGGREGATION>();
        }
    
        public int DATETIME_ID { get; set; }
        public string DAY_CODE { get; set; }
        public string DAY_FULL_CN { get; set; }
        public string DAY_FULL_EN { get; set; }
        public string DAY_SHORT_CN { get; set; }
        public string DAY_SHORT_EN { get; set; }
        public string WEEK_CODE { get; set; }
        public string WEEK_FULL_CN { get; set; }
        public string WEEK_FULL_EN { get; set; }
        public string WEEK_SHORT_CN { get; set; }
        public string WEEK_SHORT_EN { get; set; }
        public string TEN_DAY_CODE { get; set; }
        public string TEN_DAY_FULL_CN { get; set; }
        public string TEN_DAY_FULL_EN { get; set; }
        public string TEN_DAY_SHORT_CN { get; set; }
        public string TEN_DAY_SHORT_EN { get; set; }
        public string MONTH_CODE { get; set; }
        public string MONTH_FULL_CN { get; set; }
        public string MONTH_FULL_EN { get; set; }
        public string MONTH_SHORT_CN { get; set; }
        public string MONTH_SHORT_EN { get; set; }
        public string QUARTER_CODE { get; set; }
        public string QUARTER_FULL_CN { get; set; }
        public string QUARTER_FULL_EN { get; set; }
        public string QUARTER_SHORT_CN { get; set; }
        public string QUARTER_SHORT_EN { get; set; }
        public string HALF_YEAR_CODE { get; set; }
        public string HALF_YEAR_FULL_CN { get; set; }
        public string HALF_YEAR_FULL_EN { get; set; }
        public string HALF_YEAR_SHORT_CN { get; set; }
        public string HALF_YEAR_SHORT_EN { get; set; }
        public string YEAR_CODE { get; set; }
        public string YEAR_FULL_CN { get; set; }
        public string YEAR_FULL_EN { get; set; }
        public string YEAR_SHORT_CN { get; set; }
        public string YEAR_SHORT_EN { get; set; }
        public string ALL_TIME_CODE { get; set; }
        public string ALL_TIME_CN { get; set; }
        public string ALL_TIME_EN { get; set; }
        public Nullable<short> DAY_TIMESPAN { get; set; }
        public string DAY_END_DATE { get; set; }
        public Nullable<short> WEEK_TIMESPAN { get; set; }
        public string WEEK_END_DATE { get; set; }
        public Nullable<short> TEN_DAY_TIMESPAN { get; set; }
        public string TEN_DAY_END_DATE { get; set; }
        public Nullable<short> MONTH_TIMESPAN { get; set; }
        public string MONTH_END_DATE { get; set; }
        public Nullable<short> QUARTER_TIMESPAN { get; set; }
        public string QUARTER_END_DATE { get; set; }
        public Nullable<short> HALF_YEAR_TIMESPAN { get; set; }
        public string HALF_YEAR_END_DATE { get; set; }
        public Nullable<short> YEAR_TIMESPAN { get; set; }
        public string YEAR_END_DATE { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<T_AGG__DAY_SAFETY_FACTOR_SCORE> T_AGG__DAY_SAFETY_FACTOR_SCORE { get; set; }
        public virtual ICollection<T_AGG__DAY_STRUCTURE_SCORE> T_AGG__DAY_STRUCTURE_SCORE { get; set; }
        public virtual ICollection<T_AGG__HOUR_SAFETY_FACTOR_SCORE> T_AGG__HOUR_SAFETY_FACTOR_SCORE { get; set; }
        public virtual ICollection<T_AGG__HOUR_STRUCTURE_SCORE> T_AGG__HOUR_STRUCTURE_SCORE { get; set; }
        public virtual ICollection<T_AGG__MONTH_SAFETY_FACTOR_SCORE> T_AGG__MONTH_SAFETY_FACTOR_SCORE { get; set; }
        public virtual ICollection<T_AGG__MONTH_STRUCTURE_SCORE> T_AGG__MONTH_STRUCTURE_SCORE { get; set; }
        public virtual ICollection<T_AGG__WEEK_STRUCTURE_SCORE> T_AGG__WEEK_STRUCTURE_SCORE { get; set; }
        public virtual ICollection<T_AGG_WEEK_SAFETY_FACTOR_SCORE> T_AGG_WEEK_SAFETY_FACTOR_SCORE { get; set; }
        public virtual ICollection<T_DATA_AGGREGATION> T_DATA_AGGREGATION { get; set; }
    }
}
