//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_DAI
    {
        public int ID { get; set; }
        public Nullable<int> ORG_STRUC_ID { get; set; }
        public Nullable<int> DAI_ID { get; set; }
        public Nullable<int> DTU_ID { get; set; }
        public Nullable<int> PROTOCOL_ID { get; set; }
        public string DAI_IDENTIFICATION_CODE { get; set; }
        public Nullable<short> DAI_MODULE_NO { get; set; }
        public string DAI_LOCATION_DESCRIPTION { get; set; }
        public Nullable<decimal> DAI_LOCATION_X { get; set; }
        public Nullable<decimal> DAI_LOCATION_Y { get; set; }
        public Nullable<decimal> DAI_LOCATION_Z { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> PRODUCED_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> MRAK { get; set; }
    
        public virtual T_DIM_DAI_PRODUCT T_DIM_DAI_PRODUCT { get; set; }
        public virtual T_DIM_DAI_PRODUCT T_DIM_DAI_PRODUCT1 { get; set; }
    }
}
