//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_ROLE_RESOURCE
    {
        public int ID { get; set; }
        public short ROLE_ID { get; set; }
        public string RESOURCE_ID { get; set; }
    
        public virtual T_DIM_RESOURCE T_DIM_RESOURCE { get; set; }
        public virtual T_DIM_ROLE T_DIM_ROLE { get; set; }
    }
}
