//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_PRODUCT_CATEGORY
    {
        public T_DIM_PRODUCT_CATEGORY()
        {
            this.T_DIM_PRODUCT_TYPE = new HashSet<T_DIM_PRODUCT_TYPE>();
            this.T_DIM_SENSOR_PRODUCT = new HashSet<T_DIM_SENSOR_PRODUCT>();
        }
    
        public int PRODUCT_TYPE_KEY { get; set; }
        public string CATEGORYNAME { get; set; }
    
        public virtual ICollection<T_DIM_PRODUCT_TYPE> T_DIM_PRODUCT_TYPE { get; set; }
        public virtual ICollection<T_DIM_SENSOR_PRODUCT> T_DIM_SENSOR_PRODUCT { get; set; }
    }
}
