//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_Sensor_Init
    {
        public int SensorInitID { get; set; }
        public Nullable<int> SENSOR_ID { get; set; }
        public Nullable<decimal> SENSORINIT1 { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<byte> INITNUM { get; set; }
        public Nullable<decimal> SENSORINIT2 { get; set; }
        public Nullable<decimal> SENSORINIT3 { get; set; }
    
        public virtual T_DIM_SENSOR T_DIM_SENSOR { get; set; }
    }
}
