//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_REGION
    {
        public T_DIM_REGION()
        {
            this.T_DIM_COMPANY = new HashSet<T_DIM_COMPANY>();
            this.T_DIM_ORGANIZATION = new HashSet<T_DIM_ORGANIZATION>();
            this.T_DIM_STRUCTURE = new HashSet<T_DIM_STRUCTURE>();
        }
    
        public int REGION_ID { get; set; }
        public Nullable<int> PARENT_REGION_ID { get; set; }
        public string REGION_NAME_CN { get; set; }
        public string REGION_FULL_NAME_CN { get; set; }
        public string REGION_NAME_EN { get; set; }
        public string REGION_FULL_NAME_EN { get; set; }
        public Nullable<short> REGION_TYPE_ID { get; set; }
        public string ZIPCODE { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<T_DIM_COMPANY> T_DIM_COMPANY { get; set; }
        public virtual ICollection<T_DIM_ORGANIZATION> T_DIM_ORGANIZATION { get; set; }
        public virtual T_DIM_REGION_TYPE T_DIM_REGION_TYPE { get; set; }
        public virtual ICollection<T_DIM_STRUCTURE> T_DIM_STRUCTURE { get; set; }
    }
}
