//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_AGG_TYPE
    {
        public T_DIM_AGG_TYPE()
        {
            this.T_DATA_AGGREGATION = new HashSet<T_DATA_AGGREGATION>();
            this.T_DIM_AGG_CONFIG = new HashSet<T_DIM_AGG_CONFIG>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<T_DATA_AGGREGATION> T_DATA_AGGREGATION { get; set; }
        public virtual ICollection<T_DIM_AGG_CONFIG> T_DIM_AGG_CONFIG { get; set; }
    }
}
