//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_RESOURCE
    {
        public T_DIM_RESOURCE()
        {
            this.T_DIM_RESOURCE_API = new HashSet<T_DIM_RESOURCE_API>();
            this.T_DIM_ROLE_RESOURCE = new HashSet<T_DIM_ROLE_RESOURCE>();
        }
    
        public string RESOURCE_ID { get; set; }
        public string RESOURCE_NAME { get; set; }
        public string PARENT_ID { get; set; }
        public Nullable<int> RESOURCE_TYPE { get; set; }
        public string RESOURCE_MENU { get; set; }
        public string RESOURCE_ELEMENT { get; set; }
        public string RESOURCE_API { get; set; }
        public string RESOURCE_DESC { get; set; }
    
        public virtual ICollection<T_DIM_RESOURCE_API> T_DIM_RESOURCE_API { get; set; }
        public virtual ICollection<T_DIM_ROLE_RESOURCE> T_DIM_ROLE_RESOURCE { get; set; }
    }
}
