//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_OPERATION_LOG
    {
        public long OPERATION_LOG_ID { get; set; }
        public Nullable<byte> OPERATION_TYPE_ID { get; set; }
        public Nullable<byte> OPERATION_OBJECT_ID { get; set; }
        public string OPERATION_CONTENT_CN { get; set; }
        public string OPERATION_CONTENT_EN { get; set; }
        public string OPERATOR_ID { get; set; }
        public string OPERATOR_SOURCE_IP { get; set; }
        public Nullable<System.DateTime> LOG_GENERATE_DATETIME { get; set; }
        public Nullable<System.DateTime> LOG_UPDATE_DATETIME { get; set; }
        public Nullable<bool> LOG_VISIBLE_FLAG { get; set; }
    
        public virtual T_DIM_OPERATION_TYPE T_DIM_OPERATION_TYPE { get; set; }
        public virtual T_DIM_OPERATION_RESOURCE T_DIM_OPERATION_RESOURCE { get; set; }
    }
}
