//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_HOUR
    {
        public T_DIM_HOUR()
        {
            this.T_AGG__HOUR_SAFETY_FACTOR_SCORE = new HashSet<T_AGG__HOUR_SAFETY_FACTOR_SCORE>();
            this.T_AGG__HOUR_STRUCTURE_SCORE = new HashSet<T_AGG__HOUR_STRUCTURE_SCORE>();
        }
    
        public short H_ID { get; set; }
        public string H_SECTION { get; set; }
        public string H_START { get; set; }
        public string H_END { get; set; }
    
        public virtual ICollection<T_AGG__HOUR_SAFETY_FACTOR_SCORE> T_AGG__HOUR_SAFETY_FACTOR_SCORE { get; set; }
        public virtual ICollection<T_AGG__HOUR_STRUCTURE_SCORE> T_AGG__HOUR_STRUCTURE_SCORE { get; set; }
    }
}
