//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FACT_DEFAULTSENSOR_THRESHOLD
    {
        public int ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<decimal> THRESHOLD_UP_VALUE_1 { get; set; }
        public Nullable<decimal> THRESHOLD_DOWN_VALUE_1 { get; set; }
        public Nullable<byte> THRESHOLD_LEVEL_SCORE_1 { get; set; }
        public Nullable<decimal> THRESHOLD_UP_VALUE_2 { get; set; }
        public Nullable<decimal> THRESHOLD_DOWN_VALUE_2 { get; set; }
        public Nullable<byte> THRESHOLD_LEVEL_SCORE_2 { get; set; }
        public Nullable<decimal> THRESHOLD_UP_VALUE_3 { get; set; }
        public Nullable<decimal> THRESHOLD_DOWN_VALUE_3 { get; set; }
        public Nullable<byte> THRESHOLD_LEVEL_SCORE_3 { get; set; }
        public Nullable<decimal> THRESHOLD_UP_VALUE_4 { get; set; }
        public Nullable<decimal> THRESHOLD_DOWN_VALUE_4 { get; set; }
        public Nullable<byte> THRESHOLD_LEVEL_SCORE_4 { get; set; }
    }
}
