//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FACT_NORMALIZED
    {
        public int THRESHOLD_CONFIG_ID { get; set; }
        public Nullable<byte> X_AXIS_WEIGHTS { get; set; }
        public Nullable<byte> Y_AXIS_WEIGHTS { get; set; }
        public Nullable<byte> Z_AXIS_WEIGHTS { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
