//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REPORT_COLLECTION
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> StructId { get; set; }
        public Nullable<int> FactorId { get; set; }
        public Nullable<int> RptType { get; set; }
        public int DateType { get; set; }
        public string FileFullName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public string UnconfirmedFileUrl { get; set; }
        public Nullable<System.DateTime> UnconfirmedDate { get; set; }
        public string ManualFileName { get; set; }
    }
}
