//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REPORT_CONFIG
    {
        public T_REPORT_CONFIG()
        {
            this.T_REPORT_CONFIG_TEMPLATE = new HashSet<T_REPORT_CONFIG_TEMPLATE>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> StructId { get; set; }
        public Nullable<int> FactorId { get; set; }
        public Nullable<int> RptType { get; set; }
        public int DateType { get; set; }
        public string ReportName { get; set; }
        public bool IsEnabled { get; set; }
        public string CreateInterval { get; set; }
        public bool NeedConfirmed { get; set; }
        public string GetDataTime { get; set; }
    
        public virtual ICollection<T_REPORT_CONFIG_TEMPLATE> T_REPORT_CONFIG_TEMPLATE { get; set; }
    }
}
