//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TASK_INSTANT
    {
        public int ID { get; set; }
        public int DTU_ID { get; set; }
        public string SENSORS { get; set; }
        public string TASK_NAME { get; set; }
        public string REQUESTER { get; set; }
        public Nullable<System.DateTime> REQUESTED { get; set; }
        public Nullable<System.DateTime> FINISHED { get; set; }
        public int STATUS { get; set; }
        public Nullable<int> ELAPSED { get; set; }
        public Nullable<int> RESULT_CODE { get; set; }
        public string RESULT_MSG { get; set; }
        public string REQUEST_JSON { get; set; }
        public string RESULT_JSON { get; set; }
        public string MSG_ID { get; set; }
    }
}
