//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_THEMES_VIBRATION_BATCH_ARCHIVE
    {
        public System.Guid BatchId { get; set; }
        public int SensorId { get; set; }
        public int MaxFrequency { get; set; }
        public System.DateTime CollectTime { get; set; }
    }
}
