//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_THEMES_VIBRATION_MICROSEISMIC
    {
        public T_THEMES_VIBRATION_MICROSEISMIC()
        {
            this.T_THEMES_VIBRATION_MICROSEISMIC_PTSELECT = new HashSet<T_THEMES_VIBRATION_MICROSEISMIC_PTSELECT>();
        }
    
        public int Id { get; set; }
        public int struct_Id { get; set; }
        public System.DateTime CollectTime { get; set; }
        public decimal Coordinate_X { get; set; }
        public decimal Coordinate_Y { get; set; }
        public decimal Coordinate_Z { get; set; }
        public decimal Intensity { get; set; }
        public System.DateTime OccurrenceTime { get; set; }
    
        public virtual ICollection<T_THEMES_VIBRATION_MICROSEISMIC_PTSELECT> T_THEMES_VIBRATION_MICROSEISMIC_PTSELECT { get; set; }
    }
}
