//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_THEMES_ENVI_SATURATION_LINE
    {
        public int ID { get; set; }
        public int SENSOR_ID { get; set; }
        public int SAFETY_FACTOR_TYPE_ID { get; set; }
        public Nullable<decimal> HOLE_DIS { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public System.DateTime ACQUISITION_DATETIME { get; set; }
    }
}
