//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_THEMES_VIBRATION_MICROSEISMIC_PTSELECT
    {
        public int Id { get; set; }
        public int msId { get; set; }
        public Nullable<int> SelectPt { get; set; }
        public decimal SelectTime { get; set; }
        public decimal WaveSpeed { get; set; }
    
        public virtual T_THEMES_VIBRATION_MICROSEISMIC T_THEMES_VIBRATION_MICROSEISMIC { get; set; }
    }
}
