//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeSun.FS_SMISCloud.Server.CloudApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDeviceToken
    {
        public int ID { get; set; }
        public int USER_NO { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<System.DateTime> LoginDateTime { get; set; }
    
        public virtual T_DIM_USER T_DIM_USER { get; set; }
    }
}
