//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Agg.Process
{
    using Agg.Comm.DataModle;

    internal class AvgProcess : AggProcessBase
    {
        protected override double GetAggValue(List<double> data)
        {
            return data.Average();
        }

    }
}


