//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_API_LOG
    {
        public int Id { get; set; }
        public System.DateTime LogTime { get; set; }
        public string ClientIP { get; set; }
        public string UserAgent { get; set; }
        public string ClientType { get; set; }
        public string Url { get; set; }
        public string Method { get; set; }
        public string Parameter { get; set; }
        public string ParameterShow { get; set; }
        public string Content { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public int StatusCode { get; set; }
        public decimal Duration { get; set; }
        public Nullable<int> UserNo { get; set; }
        public string SessionId { get; set; }
        public bool IsVisible { get; set; }
    }
}
