//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DATA_AGGREGATION
    {
        public int Id { get; set; }
        public int SensorId { get; set; }
        public Nullable<decimal> PreviousValue1 { get; set; }
        public Nullable<decimal> CurrentValue1 { get; set; }
        public Nullable<decimal> Dlt1 { get; set; }
        public Nullable<decimal> Speed1 { get; set; }
        public Nullable<decimal> Acc1 { get; set; }
        public Nullable<decimal> PreviousValue2 { get; set; }
        public Nullable<decimal> CurrentValue2 { get; set; }
        public Nullable<decimal> Dlt2 { get; set; }
        public Nullable<decimal> Speed2 { get; set; }
        public Nullable<decimal> Acc2 { get; set; }
        public Nullable<decimal> PreviousValue3 { get; set; }
        public Nullable<decimal> CurrentValue3 { get; set; }
        public Nullable<decimal> Dlt3 { get; set; }
        public Nullable<decimal> Speed3 { get; set; }
        public Nullable<decimal> Acc3 { get; set; }
        public Nullable<decimal> PreviousValue4 { get; set; }
        public Nullable<decimal> CurrentValue4 { get; set; }
        public Nullable<decimal> Dlt4 { get; set; }
        public Nullable<decimal> Speed4 { get; set; }
        public Nullable<decimal> Acc4 { get; set; }
        public int Type { get; set; }
        public System.DateTime CollectTime { get; set; }
    }
}
