//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_GROUP_TYPE
    {
        public T_DIM_GROUP_TYPE()
        {
            this.T_DIM_GROUP = new HashSet<T_DIM_GROUP>();
        }
    
        public int GROUP_TYPE_ID { get; set; }
        public string GROUP_TYPE_NAME { get; set; }
        public string GROUP_DESCRIPTION { get; set; }
        public string SENSOR_GROUP_TABLENAME { get; set; }
    
        public virtual ICollection<T_DIM_GROUP> T_DIM_GROUP { get; set; }
    }
}
