//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_SAFETY_FACTOR_TYPE
    {
        public T_DIM_SAFETY_FACTOR_TYPE()
        {
            this.T_AGG__DAY_SAFETY_FACTOR_SCORE = new HashSet<T_AGG__DAY_SAFETY_FACTOR_SCORE>();
            this.T_AGG__HOUR_SAFETY_FACTOR_SCORE = new HashSet<T_AGG__HOUR_SAFETY_FACTOR_SCORE>();
            this.T_AGG__MONTH_SAFETY_FACTOR_SCORE = new HashSet<T_AGG__MONTH_SAFETY_FACTOR_SCORE>();
            this.T_AGG_WEEK_SAFETY_FACTOR_SCORE = new HashSet<T_AGG_WEEK_SAFETY_FACTOR_SCORE>();
            this.T_DIM_STRUCTURE_FACTOR = new HashSet<T_DIM_STRUCTURE_FACTOR>();
            this.T_THEMES_FORCE_EARTH_PRESSURE = new HashSet<T_THEMES_FORCE_EARTH_PRESSURE>();
            this.T_THEMES_FORCE_STEELBAR = new HashSet<T_THEMES_FORCE_STEELBAR>();
            this.T_THEMES_DEFORMATION_DEEP_DISPLACEMENT = new HashSet<T_THEMES_DEFORMATION_DEEP_DISPLACEMENT>();
            this.T_THEMES_DEFORMATION_DEEP_DISPLACEMENT1 = new HashSet<T_THEMES_DEFORMATION_DEEP_DISPLACEMENT>();
            this.T_THEMES_DEFORMATION_SURFACE_DISPLACEMENT = new HashSet<T_THEMES_DEFORMATION_SURFACE_DISPLACEMENT>();
            this.T_THEMES_DEFORMATION_SETTLEMENT = new HashSet<T_THEMES_DEFORMATION_SETTLEMENT>();
            this.T_THEMES_STRESS_STRAIN_RETAININGWALL = new HashSet<T_THEMES_STRESS_STRAIN_RETAININGWALL>();
            this.T_THEMES_STRESS_STRAIN_PORE_WATER_PRESSURE = new HashSet<T_THEMES_STRESS_STRAIN_PORE_WATER_PRESSURE>();
            this.T_FACT_SAFETY_FACTOR_SCORE = new HashSet<T_FACT_SAFETY_FACTOR_SCORE>();
            this.T_FACT_SAFETY_FACTOR_WEIGHTS = new HashSet<T_FACT_SAFETY_FACTOR_WEIGHTS>();
            this.T_FACT_SUB_SAFETY_FACTOR_WEIGHTS = new HashSet<T_FACT_SUB_SAFETY_FACTOR_WEIGHTS>();
            this.T_THEMES_ENVI_RAINFALL = new HashSet<T_THEMES_ENVI_RAINFALL>();
            this.T_THEMES_ENVI_TEMP_HUMI = new HashSet<T_THEMES_ENVI_TEMP_HUMI>();
            this.T_THEMES_FORCE_ANCHOR = new HashSet<T_THEMES_FORCE_ANCHOR>();
            this.T_DIM_SENSOR = new HashSet<T_DIM_SENSOR>();
            this.T_THEMES_DEFORMATION_DEEP_DISPLACEMENT_DAILY = new HashSet<T_THEMES_DEFORMATION_DEEP_DISPLACEMENT_DAILY>();
            this.T_THEMES_ENVI_WATER_LEVEL = new HashSet<T_THEMES_ENVI_WATER_LEVEL>();
        }
    
        public int SAFETY_FACTOR_TYPE_ID { get; set; }
        public Nullable<int> SAFETY_FACTOR_TYPE_PARENT_ID { get; set; }
        public string SAFETY_FACTOR_TYPE_NAME { get; set; }
        public string SAFETY_FACTOR_TYPE_NAME_EN { get; set; }
        public Nullable<int> FACTOR_VALUE_COLUMN_NUMBER { get; set; }
        public string FACTOR_VALUE_COLUMNS { get; set; }
        public string FACTOR_VALUE_DECIMAL_PLACES { get; set; }
        public string FACTOR_VALUE_UNIT { get; set; }
        public Nullable<byte> SAFETY_FACTOR_FLAG { get; set; }
        public string SAFETY_FACTOR_TYPE_COLOR { get; set; }
        public string IMG_SRC { get; set; }
        public string THEMES_TABLE_NAME { get; set; }
        public string THEMES_COLUMNS { get; set; }
        public string DESCRIPTION { get; set; }
        public string ORIGINAL_TABLE_NAME { get; set; }
        public string ORIGINAL_COLUMNS { get; set; }
    
        public virtual ICollection<T_AGG__DAY_SAFETY_FACTOR_SCORE> T_AGG__DAY_SAFETY_FACTOR_SCORE { get; set; }
        public virtual ICollection<T_AGG__HOUR_SAFETY_FACTOR_SCORE> T_AGG__HOUR_SAFETY_FACTOR_SCORE { get; set; }
        public virtual ICollection<T_AGG__MONTH_SAFETY_FACTOR_SCORE> T_AGG__MONTH_SAFETY_FACTOR_SCORE { get; set; }
        public virtual ICollection<T_AGG_WEEK_SAFETY_FACTOR_SCORE> T_AGG_WEEK_SAFETY_FACTOR_SCORE { get; set; }
        public virtual ICollection<T_DIM_STRUCTURE_FACTOR> T_DIM_STRUCTURE_FACTOR { get; set; }
        public virtual ICollection<T_THEMES_FORCE_EARTH_PRESSURE> T_THEMES_FORCE_EARTH_PRESSURE { get; set; }
        public virtual ICollection<T_THEMES_FORCE_STEELBAR> T_THEMES_FORCE_STEELBAR { get; set; }
        public virtual ICollection<T_THEMES_DEFORMATION_DEEP_DISPLACEMENT> T_THEMES_DEFORMATION_DEEP_DISPLACEMENT { get; set; }
        public virtual ICollection<T_THEMES_DEFORMATION_DEEP_DISPLACEMENT> T_THEMES_DEFORMATION_DEEP_DISPLACEMENT1 { get; set; }
        public virtual ICollection<T_THEMES_DEFORMATION_SURFACE_DISPLACEMENT> T_THEMES_DEFORMATION_SURFACE_DISPLACEMENT { get; set; }
        public virtual ICollection<T_THEMES_DEFORMATION_SETTLEMENT> T_THEMES_DEFORMATION_SETTLEMENT { get; set; }
        public virtual ICollection<T_THEMES_STRESS_STRAIN_RETAININGWALL> T_THEMES_STRESS_STRAIN_RETAININGWALL { get; set; }
        public virtual ICollection<T_THEMES_STRESS_STRAIN_PORE_WATER_PRESSURE> T_THEMES_STRESS_STRAIN_PORE_WATER_PRESSURE { get; set; }
        public virtual ICollection<T_FACT_SAFETY_FACTOR_SCORE> T_FACT_SAFETY_FACTOR_SCORE { get; set; }
        public virtual ICollection<T_FACT_SAFETY_FACTOR_WEIGHTS> T_FACT_SAFETY_FACTOR_WEIGHTS { get; set; }
        public virtual ICollection<T_FACT_SUB_SAFETY_FACTOR_WEIGHTS> T_FACT_SUB_SAFETY_FACTOR_WEIGHTS { get; set; }
        public virtual ICollection<T_THEMES_ENVI_RAINFALL> T_THEMES_ENVI_RAINFALL { get; set; }
        public virtual ICollection<T_THEMES_ENVI_TEMP_HUMI> T_THEMES_ENVI_TEMP_HUMI { get; set; }
        public virtual ICollection<T_THEMES_FORCE_ANCHOR> T_THEMES_FORCE_ANCHOR { get; set; }
        public virtual ICollection<T_DIM_SENSOR> T_DIM_SENSOR { get; set; }
        public virtual ICollection<T_THEMES_DEFORMATION_DEEP_DISPLACEMENT_DAILY> T_THEMES_DEFORMATION_DEEP_DISPLACEMENT_DAILY { get; set; }
        public virtual ICollection<T_THEMES_ENVI_WATER_LEVEL> T_THEMES_ENVI_WATER_LEVEL { get; set; }
    }
}
