//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_POWER_SUPPLY_TYPE
    {
        public T_DIM_POWER_SUPPLY_TYPE()
        {
            this.T_DIM_DAI_PRODUCT = new HashSet<T_DIM_DAI_PRODUCT>();
        }
    
        public short POWER_SUPPLY_TYPE_ID { get; set; }
        public Nullable<short> POWER_SUPPLY__TYPE { get; set; }
        public string VOLTAGE_RANGE { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<T_DIM_DAI_PRODUCT> T_DIM_DAI_PRODUCT { get; set; }
    }
}
