//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_PROTOCOL_TYPE
    {
        public T_DIM_PROTOCOL_TYPE()
        {
            this.T_DIM_DAI_PRODUCT = new HashSet<T_DIM_DAI_PRODUCT>();
            this.T_DIM_PROTOCOLCOMMAND = new HashSet<T_DIM_PROTOCOLCOMMAND>();
            this.T_DIM_SENSOR_PRODUCT = new HashSet<T_DIM_SENSOR_PRODUCT>();
        }
    
        public short PROTOCOL_ID { get; set; }
        public string PROTOCOL_CODE { get; set; }
        public string PROTOCOL_TYPE { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<T_DIM_DAI_PRODUCT> T_DIM_DAI_PRODUCT { get; set; }
        public virtual ICollection<T_DIM_PROTOCOLCOMMAND> T_DIM_PROTOCOLCOMMAND { get; set; }
        public virtual ICollection<T_DIM_SENSOR_PRODUCT> T_DIM_SENSOR_PRODUCT { get; set; }
    }
}
