//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_COMPANY
    {
        public int ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public Nullable<int> COMPANY_REGION_ID { get; set; }
        public string COMPANY_ADDRESS { get; set; }
        public string COMPANY_PHONE_NUMBER { get; set; }
        public string COMPANY_FAX { get; set; }
        public string COMPANY_WEBSITE { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_FIXED_PHONE_NUMBER { get; set; }
        public string CONTACT_MOBILE__PHONE_NUMBER { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual T_DIM_REGION T_DIM_REGION { get; set; }
    }
}
