//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_STRUCTURE
    {
        public T_DIM_STRUCTURE()
        {
            this.T_DIM_ORG_STUCTURE = new HashSet<T_DIM_ORG_STUCTURE>();
            this.T_DIM_SECTION = new HashSet<T_DIM_SECTION>();
            this.T_DIM_STRUCT_DTU = new HashSet<T_DIM_STRUCT_DTU>();
            this.T_DIM_STRUCTURE_FACTOR = new HashSet<T_DIM_STRUCTURE_FACTOR>();
            this.T_WARNING_SENSOR = new HashSet<T_WARNING_SENSOR>();
        }
    
        public int ID { get; set; }
        public string STRUCTURE_TYPE_ID { get; set; }
        public string STRUCTURE_NAME_CN { get; set; }
        public string STRUCTURE_NAME_EN { get; set; }
        public string STRUCTURE_ALIAS_CN { get; set; }
        public string STRUCTURE_ALIAS_EN { get; set; }
        public string STRUCTURE_TRIAL_CN { get; set; }
        public string STRUCTURE_TRIAL_EN { get; set; }
        public Nullable<int> STRUCTURE_REGION { get; set; }
        public string STRUCTURE_DETAIL_ADDRESS { get; set; }
        public Nullable<decimal> STRUCTURE_LONGITUDE { get; set; }
        public Nullable<decimal> STRUCTURE_LATITUDE { get; set; }
        public string CONSTRUCTION_COMPANY_NAME { get; set; }
        public Nullable<System.DateTime> CONSTRUCTION_DATE { get; set; }
        public Nullable<int> USEFUL_LIFE { get; set; }
        public byte[] STRUCTURE_HOT_SPOT_MAP { get; set; }
        public Nullable<int> STRUCTURE_HOT_SPOT_MAP_TYPE { get; set; }
        public byte[] PIC_BIG_STRUCTURE { get; set; }
        public byte[] PIC_MEDIUM_STRUCTURE { get; set; }
        public byte[] PIC_SMALL_STRUCTURE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> STRUCTURE_ALTITUDE { get; set; }
        public string Imagename { get; set; }
        public int IsDelete { get; set; }
        public string RegionPath { get; set; }
        public string StructureTypePath { get; set; }
        public Nullable<int> ProjectStatus { get; set; }
    
        public virtual ICollection<T_DIM_ORG_STUCTURE> T_DIM_ORG_STUCTURE { get; set; }
        public virtual T_DIM_REGION T_DIM_REGION { get; set; }
        public virtual ICollection<T_DIM_SECTION> T_DIM_SECTION { get; set; }
        public virtual ICollection<T_DIM_STRUCT_DTU> T_DIM_STRUCT_DTU { get; set; }
        public virtual ICollection<T_DIM_STRUCTURE_FACTOR> T_DIM_STRUCTURE_FACTOR { get; set; }
        public virtual T_DIM_STRUCTURE_TYPE T_DIM_STRUCTURE_TYPE { get; set; }
        public virtual ICollection<T_WARNING_SENSOR> T_WARNING_SENSOR { get; set; }
    }
}
