//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_ORG_STUCTURE
    {
        public T_DIM_ORG_STUCTURE()
        {
            this.T_AGG__DAY_SAFETY_FACTOR_SCORE = new HashSet<T_AGG__DAY_SAFETY_FACTOR_SCORE>();
            this.T_AGG__DAY_STRUCTURE_SCORE = new HashSet<T_AGG__DAY_STRUCTURE_SCORE>();
            this.T_AGG__HOUR_SAFETY_FACTOR_SCORE = new HashSet<T_AGG__HOUR_SAFETY_FACTOR_SCORE>();
            this.T_AGG__HOUR_STRUCTURE_SCORE = new HashSet<T_AGG__HOUR_STRUCTURE_SCORE>();
            this.T_AGG__MONTH_SAFETY_FACTOR_SCORE = new HashSet<T_AGG__MONTH_SAFETY_FACTOR_SCORE>();
            this.T_AGG__MONTH_STRUCTURE_SCORE = new HashSet<T_AGG__MONTH_STRUCTURE_SCORE>();
            this.T_AGG__WEEK_STRUCTURE_SCORE = new HashSet<T_AGG__WEEK_STRUCTURE_SCORE>();
            this.T_AGG_WEEK_SAFETY_FACTOR_SCORE = new HashSet<T_AGG_WEEK_SAFETY_FACTOR_SCORE>();
            this.T_FACT_SUB_SAFETY_FACTOR_WEIGHTS = new HashSet<T_FACT_SUB_SAFETY_FACTOR_WEIGHTS>();
            this.T_FACT_STRUCTURE_SCORE = new HashSet<T_FACT_STRUCTURE_SCORE>();
            this.T_FACT_SAFETY_FACTOR_WEIGHTS = new HashSet<T_FACT_SAFETY_FACTOR_WEIGHTS>();
            this.T_FACT_SENSOR_WEIGHTS = new HashSet<T_FACT_SENSOR_WEIGHTS>();
            this.T_DIM_PERMISSION = new HashSet<T_DIM_PERMISSION>();
        }
    
        public int ORG_STRUC_ID { get; set; }
        public int ORGANIZATION_ID { get; set; }
        public int STRUCTURE_ID { get; set; }
        public string ABB_NAME_CN { get; set; }
        public string FULL__NAME_CN { get; set; }
        public string TRIAL_NAME_CN { get; set; }
        public string STRUCTURE_NAME_CN { get; set; }
        public string STRUCTURE_ALIAS_CN { get; set; }
        public string STRUCTURE_TRIAL_CN { get; set; }
        public Nullable<System.Guid> ACTIVATION_CODE { get; set; }
        public Nullable<System.DateTime> AggTime { get; set; }
    
        public virtual ICollection<T_AGG__DAY_SAFETY_FACTOR_SCORE> T_AGG__DAY_SAFETY_FACTOR_SCORE { get; set; }
        public virtual ICollection<T_AGG__DAY_STRUCTURE_SCORE> T_AGG__DAY_STRUCTURE_SCORE { get; set; }
        public virtual ICollection<T_AGG__HOUR_SAFETY_FACTOR_SCORE> T_AGG__HOUR_SAFETY_FACTOR_SCORE { get; set; }
        public virtual ICollection<T_AGG__HOUR_STRUCTURE_SCORE> T_AGG__HOUR_STRUCTURE_SCORE { get; set; }
        public virtual ICollection<T_AGG__MONTH_SAFETY_FACTOR_SCORE> T_AGG__MONTH_SAFETY_FACTOR_SCORE { get; set; }
        public virtual ICollection<T_AGG__MONTH_STRUCTURE_SCORE> T_AGG__MONTH_STRUCTURE_SCORE { get; set; }
        public virtual ICollection<T_AGG__WEEK_STRUCTURE_SCORE> T_AGG__WEEK_STRUCTURE_SCORE { get; set; }
        public virtual ICollection<T_AGG_WEEK_SAFETY_FACTOR_SCORE> T_AGG_WEEK_SAFETY_FACTOR_SCORE { get; set; }
        public virtual ICollection<T_FACT_SUB_SAFETY_FACTOR_WEIGHTS> T_FACT_SUB_SAFETY_FACTOR_WEIGHTS { get; set; }
        public virtual T_DIM_ORGANIZATION T_DIM_ORGANIZATION { get; set; }
        public virtual T_DIM_STRUCTURE T_DIM_STRUCTURE { get; set; }
        public virtual ICollection<T_FACT_STRUCTURE_SCORE> T_FACT_STRUCTURE_SCORE { get; set; }
        public virtual ICollection<T_FACT_SAFETY_FACTOR_WEIGHTS> T_FACT_SAFETY_FACTOR_WEIGHTS { get; set; }
        public virtual ICollection<T_FACT_SENSOR_WEIGHTS> T_FACT_SENSOR_WEIGHTS { get; set; }
        public virtual ICollection<T_DIM_PERMISSION> T_DIM_PERMISSION { get; set; }
    }
}
