//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_SENSOR_GROUP_CEXIE
    {
        public int SENSOR_GROUP_ID { get; set; }
        public int GROUP_ID { get; set; }
        public int SENSOR_ID { get; set; }
        public decimal DEPTH { get; set; }
        public decimal DISPLAY_DEPTH { get; set; }
    
        public virtual T_DIM_GROUP T_DIM_GROUP { get; set; }
        public virtual T_DIM_SENSOR T_DIM_SENSOR { get; set; }
    }
}
