//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_SENSOR
    {
        public T_DIM_SENSOR()
        {
            this.T_DIM_FORMULAID_SET = new HashSet<T_DIM_FORMULAID_SET>();
            this.T_DIM_SENSOR_GROUP_CHENJIANG = new HashSet<T_DIM_SENSOR_GROUP_CHENJIANG>();
            this.T_DIM_SENSOR_GROUP_JINRUNXIAN = new HashSet<T_DIM_SENSOR_GROUP_JINRUNXIAN>();
            this.T_DIM_SENSOR_GROUP_CEXIE = new HashSet<T_DIM_SENSOR_GROUP_CEXIE>();
            this.T_THEMES_ENVI_RAINFALL = new HashSet<T_THEMES_ENVI_RAINFALL>();
            this.T_THEMES_DEFORMATION_DEEP_DISPLACEMENT = new HashSet<T_THEMES_DEFORMATION_DEEP_DISPLACEMENT>();
            this.T_THEMES_DEFORMATION_DEEP_DISPLACEMENT1 = new HashSet<T_THEMES_DEFORMATION_DEEP_DISPLACEMENT>();
            this.T_THEMES_DEFORMATION_SURFACE_DISPLACEMENT = new HashSet<T_THEMES_DEFORMATION_SURFACE_DISPLACEMENT>();
            this.T_THEMES_ENVI_TEMP_HUMI = new HashSet<T_THEMES_ENVI_TEMP_HUMI>();
            this.T_THEMES_FORCE_ANCHOR = new HashSet<T_THEMES_FORCE_ANCHOR>();
            this.T_THEMES_DEFORMATION_SETTLEMENT = new HashSet<T_THEMES_DEFORMATION_SETTLEMENT>();
            this.T_THEMES_STRESS_STRAIN_PORE_WATER_PRESSURE = new HashSet<T_THEMES_STRESS_STRAIN_PORE_WATER_PRESSURE>();
            this.T_THEMES_FORCE_EARTH_PRESSURE = new HashSet<T_THEMES_FORCE_EARTH_PRESSURE>();
            this.T_THEMES_FORCE_STEELBAR = new HashSet<T_THEMES_FORCE_STEELBAR>();
            this.T_THEMES_STRESS_STRAIN_RETAININGWALL = new HashSet<T_THEMES_STRESS_STRAIN_RETAININGWALL>();
            this.T_FACT_SENSOR_WEIGHTS = new HashSet<T_FACT_SENSOR_WEIGHTS>();
            this.T_DIM_SENSOR_DATASTATUS = new HashSet<T_DIM_SENSOR_DATASTATUS>();
            this.T_DIM_Sensor_Init = new HashSet<T_DIM_Sensor_Init>();
            this.T_DIM_SENSOR_CORRENT = new HashSet<T_DIM_SENSOR_CORRENT>();
            this.T_THEMES_DEFORMATION_DEEP_DISPLACEMENT_DAILY = new HashSet<T_THEMES_DEFORMATION_DEEP_DISPLACEMENT_DAILY>();
            this.T_THEMES_ENVI_WATER_LEVEL = new HashSet<T_THEMES_ENVI_WATER_LEVEL>();
        }
    
        public int SENSOR_ID { get; set; }
        public int PRODUCT_SENSOR_ID { get; set; }
        public Nullable<byte> DAI_CHANNEL_NUMBER { get; set; }
        public string SENSOR_IDENTIFICATION_CODE { get; set; }
        public string SENSOR_LOCATION_DESCRIPTION { get; set; }
        public Nullable<decimal> SENSOR_LOCATION_X { get; set; }
        public Nullable<decimal> SENSOR_LOCATION_Y { get; set; }
        public Nullable<decimal> SENSOR_LOCATION_Z { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> PRODUCED_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public bool IsDeleted { get; set; }
        public string RESERVED_FIELD_4 { get; set; }
        public string RESERVED_FIELD_5 { get; set; }
        public Nullable<int> SAFETY_FACTOR_TYPE_ID { get; set; }
        public Nullable<int> STRUCT_ID { get; set; }
        public Nullable<int> DTU_ID { get; set; }
        public Nullable<int> MODULE_NO { get; set; }
        public int Identification { get; set; }
        public Nullable<int> SensorGranularity { get; set; }
    
        public virtual ICollection<T_DIM_FORMULAID_SET> T_DIM_FORMULAID_SET { get; set; }
        public virtual T_DIM_SAFETY_FACTOR_TYPE T_DIM_SAFETY_FACTOR_TYPE { get; set; }
        public virtual ICollection<T_DIM_SENSOR_GROUP_CHENJIANG> T_DIM_SENSOR_GROUP_CHENJIANG { get; set; }
        public virtual ICollection<T_DIM_SENSOR_GROUP_JINRUNXIAN> T_DIM_SENSOR_GROUP_JINRUNXIAN { get; set; }
        public virtual ICollection<T_DIM_SENSOR_GROUP_CEXIE> T_DIM_SENSOR_GROUP_CEXIE { get; set; }
        public virtual ICollection<T_THEMES_ENVI_RAINFALL> T_THEMES_ENVI_RAINFALL { get; set; }
        public virtual T_DIM_SENSOR_PRODUCT T_DIM_SENSOR_PRODUCT { get; set; }
        public virtual ICollection<T_THEMES_DEFORMATION_DEEP_DISPLACEMENT> T_THEMES_DEFORMATION_DEEP_DISPLACEMENT { get; set; }
        public virtual ICollection<T_THEMES_DEFORMATION_DEEP_DISPLACEMENT> T_THEMES_DEFORMATION_DEEP_DISPLACEMENT1 { get; set; }
        public virtual ICollection<T_THEMES_DEFORMATION_SURFACE_DISPLACEMENT> T_THEMES_DEFORMATION_SURFACE_DISPLACEMENT { get; set; }
        public virtual ICollection<T_THEMES_ENVI_TEMP_HUMI> T_THEMES_ENVI_TEMP_HUMI { get; set; }
        public virtual ICollection<T_THEMES_FORCE_ANCHOR> T_THEMES_FORCE_ANCHOR { get; set; }
        public virtual ICollection<T_THEMES_DEFORMATION_SETTLEMENT> T_THEMES_DEFORMATION_SETTLEMENT { get; set; }
        public virtual ICollection<T_THEMES_STRESS_STRAIN_PORE_WATER_PRESSURE> T_THEMES_STRESS_STRAIN_PORE_WATER_PRESSURE { get; set; }
        public virtual ICollection<T_THEMES_FORCE_EARTH_PRESSURE> T_THEMES_FORCE_EARTH_PRESSURE { get; set; }
        public virtual ICollection<T_THEMES_FORCE_STEELBAR> T_THEMES_FORCE_STEELBAR { get; set; }
        public virtual ICollection<T_THEMES_STRESS_STRAIN_RETAININGWALL> T_THEMES_STRESS_STRAIN_RETAININGWALL { get; set; }
        public virtual ICollection<T_FACT_SENSOR_WEIGHTS> T_FACT_SENSOR_WEIGHTS { get; set; }
        public virtual ICollection<T_DIM_SENSOR_DATASTATUS> T_DIM_SENSOR_DATASTATUS { get; set; }
        public virtual ICollection<T_DIM_Sensor_Init> T_DIM_Sensor_Init { get; set; }
        public virtual ICollection<T_DIM_SENSOR_CORRENT> T_DIM_SENSOR_CORRENT { get; set; }
        public virtual ICollection<T_THEMES_DEFORMATION_DEEP_DISPLACEMENT_DAILY> T_THEMES_DEFORMATION_DEEP_DISPLACEMENT_DAILY { get; set; }
        public virtual ICollection<T_THEMES_ENVI_WATER_LEVEL> T_THEMES_ENVI_WATER_LEVEL { get; set; }
    }
}
