//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_STRUCTUER_LINE
    {
        public T_DIM_STRUCTUER_LINE()
        {
            this.T_DIM_STRUCTUER_PROGRESS = new HashSet<T_DIM_STRUCTUER_PROGRESS>();
        }
    
        public int Id { get; set; }
        public string Line_Name { get; set; }
        public decimal Line_Length { get; set; }
        public string Start_Id { get; set; }
        public string End_Id { get; set; }
        public int Structure_Id { get; set; }
        public string Color { get; set; }
        public string Unit { get; set; }
    
        public virtual ICollection<T_DIM_STRUCTUER_PROGRESS> T_DIM_STRUCTUER_PROGRESS { get; set; }
    }
}
