//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_dim_Dictionary
    {
        public int DictId { get; set; }
        public int DictType { get; set; }
        public int DictClass { get; set; }
        public string DictName { get; set; }
        public Nullable<decimal> DictValue { get; set; }
        public Nullable<short> IsDel { get; set; }
        public Nullable<short> IsLock { get; set; }
        public string Remark { get; set; }
    }
}
