//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIM_ORGANIZATION
    {
        public T_DIM_ORGANIZATION()
        {
            this.T_DIM_ORG_STUCTURE = new HashSet<T_DIM_ORG_STUCTURE>();
            this.T_DIM_USER_ORG = new HashSet<T_DIM_USER_ORG>();
        }
    
        public int ID { get; set; }
        public string ABB_NAME_EN { get; set; }
        public string ABB_NAME_CN { get; set; }
        public string FULL_NAME_EN { get; set; }
        public string FULL_NAME_CN { get; set; }
        public Nullable<int> REGION_ID { get; set; }
        public string ADDRESS_STREET_CN { get; set; }
        public string ADDRESS_STREET_EN { get; set; }
        public string FIXED_PHONE_NUMBER { get; set; }
        public string FAX_NUMBER { get; set; }
        public string MOBILE_PHONE_NUMBER { get; set; }
        public string ZIPCODE { get; set; }
        public string EMAIL { get; set; }
        public string WEBSITE { get; set; }
        public string ALIAS_ORGANIZATION_CN { get; set; }
        public string ALIAS_ORGANIZATION_EN { get; set; }
        public string TRIAL_NAME_CN { get; set; }
        public string TRIAL_NAME_EN { get; set; }
        public byte[] PIC_BIG_ORGANIZATION { get; set; }
        public byte[] PIC_MEDIUM_ORGANIZATION { get; set; }
        public byte[] PIC_SMALL_ORGANIZATION { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<int> ORDERBY_COLUMN { get; set; }
        public Nullable<int> ProvinceCode { get; set; }
        public Nullable<int> CityCode { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public bool IsDeleted { get; set; }
        public string SystemName { get; set; }
        public string Logo { get; set; }
    
        public virtual ICollection<T_DIM_ORG_STUCTURE> T_DIM_ORG_STUCTURE { get; set; }
        public virtual T_DIM_REGION T_DIM_REGION { get; set; }
        public virtual ICollection<T_DIM_USER_ORG> T_DIM_USER_ORG { get; set; }
    }
}
