//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FACT_SAFETY_FACTOR_WEIGHTS
    {
        public int SAFETY_FACTOR_WEIGHTS_ID { get; set; }
        public Nullable<int> ORG_STRUC_ID { get; set; }
        public Nullable<int> SAFETY_FACTOR_TYPE_ID { get; set; }
        public Nullable<byte> SAFETY_FACTOR_WEIGHTS { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual T_DIM_ORG_STUCTURE T_DIM_ORG_STUCTURE { get; set; }
        public virtual T_DIM_SAFETY_FACTOR_TYPE T_DIM_SAFETY_FACTOR_TYPE { get; set; }
    }
}
