//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FACT_SENSOR_THRESHOLD
    {
        public int Id { get; set; }
        public int SensorId { get; set; }
        public int ItemId { get; set; }
        public int ThresholdLevel { get; set; }
        public Nullable<double> ThresholdDownValue { get; set; }
        public Nullable<double> ThresholdUpValue { get; set; }
    }
}
