//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FACT_WEIGHT_SCORE
    {
        public T_FACT_WEIGHT_SCORE()
        {
            this.T_AGG__DAY_STRUCTURE_SCORE = new HashSet<T_AGG__DAY_STRUCTURE_SCORE>();
            this.T_AGG__DAY_STRUCTURE_SCORE1 = new HashSet<T_AGG__DAY_STRUCTURE_SCORE>();
            this.T_AGG__DAY_STRUCTURE_SCORE2 = new HashSet<T_AGG__DAY_STRUCTURE_SCORE>();
            this.T_AGG__HOUR_STRUCTURE_SCORE = new HashSet<T_AGG__HOUR_STRUCTURE_SCORE>();
            this.T_AGG__HOUR_STRUCTURE_SCORE1 = new HashSet<T_AGG__HOUR_STRUCTURE_SCORE>();
            this.T_AGG__HOUR_STRUCTURE_SCORE2 = new HashSet<T_AGG__HOUR_STRUCTURE_SCORE>();
            this.T_AGG__MONTH_STRUCTURE_SCORE = new HashSet<T_AGG__MONTH_STRUCTURE_SCORE>();
            this.T_AGG__MONTH_STRUCTURE_SCORE1 = new HashSet<T_AGG__MONTH_STRUCTURE_SCORE>();
            this.T_AGG__MONTH_STRUCTURE_SCORE2 = new HashSet<T_AGG__MONTH_STRUCTURE_SCORE>();
            this.T_AGG__WEEK_STRUCTURE_SCORE = new HashSet<T_AGG__WEEK_STRUCTURE_SCORE>();
            this.T_AGG__WEEK_STRUCTURE_SCORE1 = new HashSet<T_AGG__WEEK_STRUCTURE_SCORE>();
            this.T_AGG__WEEK_STRUCTURE_SCORE2 = new HashSet<T_AGG__WEEK_STRUCTURE_SCORE>();
        }
    
        public int SCORE_ID { get; set; }
        public string SCORE_LEVEL { get; set; }
        public Nullable<byte> SCORE_VALUE_LOWER_LIMIT { get; set; }
        public Nullable<byte> SCORE_VALUE_UPPER_LIMIT { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<T_AGG__DAY_STRUCTURE_SCORE> T_AGG__DAY_STRUCTURE_SCORE { get; set; }
        public virtual ICollection<T_AGG__DAY_STRUCTURE_SCORE> T_AGG__DAY_STRUCTURE_SCORE1 { get; set; }
        public virtual ICollection<T_AGG__DAY_STRUCTURE_SCORE> T_AGG__DAY_STRUCTURE_SCORE2 { get; set; }
        public virtual ICollection<T_AGG__HOUR_STRUCTURE_SCORE> T_AGG__HOUR_STRUCTURE_SCORE { get; set; }
        public virtual ICollection<T_AGG__HOUR_STRUCTURE_SCORE> T_AGG__HOUR_STRUCTURE_SCORE1 { get; set; }
        public virtual ICollection<T_AGG__HOUR_STRUCTURE_SCORE> T_AGG__HOUR_STRUCTURE_SCORE2 { get; set; }
        public virtual ICollection<T_AGG__MONTH_STRUCTURE_SCORE> T_AGG__MONTH_STRUCTURE_SCORE { get; set; }
        public virtual ICollection<T_AGG__MONTH_STRUCTURE_SCORE> T_AGG__MONTH_STRUCTURE_SCORE1 { get; set; }
        public virtual ICollection<T_AGG__MONTH_STRUCTURE_SCORE> T_AGG__MONTH_STRUCTURE_SCORE2 { get; set; }
        public virtual ICollection<T_AGG__WEEK_STRUCTURE_SCORE> T_AGG__WEEK_STRUCTURE_SCORE { get; set; }
        public virtual ICollection<T_AGG__WEEK_STRUCTURE_SCORE> T_AGG__WEEK_STRUCTURE_SCORE1 { get; set; }
        public virtual ICollection<T_AGG__WEEK_STRUCTURE_SCORE> T_AGG__WEEK_STRUCTURE_SCORE2 { get; set; }
    }
}
