//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WARNING_SMS_RECIEVER
    {
        public int ReceiverId { get; set; }
        public string RecieverName { get; set; }
        public string RecieverPhone { get; set; }
        public int FilterLevel { get; set; }
        public int UserNo { get; set; }
        public int RoleId { get; set; }
        public Nullable<bool> ReceiveMode { get; set; }
        public string RecieverMail { get; set; }
    
        public virtual T_DIM_USER T_DIM_USER { get; set; }
    }
}
