//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WARNING_DEALDETAILS
    {
        public int Id { get; set; }
        public int WarningId { get; set; }
        public int UserNo { get; set; }
        public string Suggestion { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
    
        public virtual T_DIM_USER T_DIM_USER { get; set; }
        public virtual T_WARNING_SENSOR T_WARNING_SENSOR { get; set; }
    }
}
