//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Agg.Comm.DataModle
{
    [Serializable]
    public class AggResult
    {
        public AggResult(int structId, int factorId, string timeTag, AggType type, int configId)
        {
            this.StructId = structId;
            this.SafeFactorId = factorId;
            this.TimeTag = timeTag;
            this.AggType = type;
            this.ConfigId = configId;
        }

        public int StructId { get;  protected set;}

        public int SafeFactorId { get; protected set; }

        public int ConfigId { get; protected set; }

        /// <summary>
        /// 本次聚集的结果
        /// </summary>
        public List<AggData> AggDatas { get; set; }

        public AggType AggType { get; protected set; }

        /// <summary>
        /// 上一次聚集的数据
        /// </summary>
        public List<AggData> LastAggDatas { get; set; }

        /// <summary>
        /// 聚集数据变化量
        /// </summary>
        public List<AggData> AggDataChanges { get; set; }

        public string TimeTag { get; protected set; }

        public virtual ResultType Result
        {
            get;
            set;
        }
    }

}


