//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//---------------------------------------------------- m--------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Agg.DataPool
{
    using Agg.Comm.DataModle;

    internal class FlowDataPool : IDataPool
    {
        public BaseAggConfig Config { set; get; }

        public AggRawData GetAggRawData(DateTime nowTime)
        {
            throw new System.NotImplementedException();
        }

        public void AddNewData(AggRawData newDatas)
        {
            throw new System.NotImplementedException();
        }

        public List<AggData> GetLastAggData()
        {
            throw new System.NotImplementedException();
        }

    }

}


