//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Agg.DataPool
{
    using Agg.Comm.DataModle;
   

    public interface IDataPool
    {
        BaseAggConfig Config { set; get; }

        /// <summary>
        /// 获取待聚集的原始数据
        /// </summary>
        /// <param name="nowTime">当前时间</param>
        /// <returns></returns>
        AggRawData GetAggRawData(DateTime nowTime);

        ///// <summary>
        ///// 获取前一次聚集粒度的数据
        ///// </summary>
        ///// <returns>聚集数据</returns>
        //List<AggData> GetLastAggData(); 

        /// <summary>
        /// 增加新数据
        /// </summary>
        /// <param name="newDatas">新数据</param>
        void AddNewData(AggRawData newDatas);

    }
}


